package org;
// Generated 1/12/2014 10:39:03 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Empresacliente generated by hbm2java
 */
public class Empresacliente  implements java.io.Serializable {


     private Integer idEmpresaCliente;
     private String nombreEmpresa;
     private String numeroTel;
     private String direccion;
     private String correoElectronico;
     private Set<Srmenu> srmenus = new HashSet<Srmenu>(0);
     private Set<Srentrenimiento> srentrenimientos = new HashSet<Srentrenimiento>(0);
     private Set<Srsalon> srsalons = new HashSet<Srsalon>(0);

    public Empresacliente() {
    }

	
    public Empresacliente(String nombreEmpresa, String numeroTel, String direccion, String correoElectronico) {
        this.nombreEmpresa = nombreEmpresa;
        this.numeroTel = numeroTel;
        this.direccion = direccion;
        this.correoElectronico = correoElectronico;
    }
    public Empresacliente(String nombreEmpresa, String numeroTel, String direccion, String correoElectronico, Set<Srmenu> srmenus, Set<Srentrenimiento> srentrenimientos, Set<Srsalon> srsalons) {
       this.nombreEmpresa = nombreEmpresa;
       this.numeroTel = numeroTel;
       this.direccion = direccion;
       this.correoElectronico = correoElectronico;
       this.srmenus = srmenus;
       this.srentrenimientos = srentrenimientos;
       this.srsalons = srsalons;
    }
   
    public Integer getIdEmpresaCliente() {
        return this.idEmpresaCliente;
    }
    
    public void setIdEmpresaCliente(Integer idEmpresaCliente) {
        this.idEmpresaCliente = idEmpresaCliente;
    }
    public String getNombreEmpresa() {
        return this.nombreEmpresa;
    }
    
    public void setNombreEmpresa(String nombreEmpresa) {
        this.nombreEmpresa = nombreEmpresa;
    }
    public String getNumeroTel() {
        return this.numeroTel;
    }
    
    public void setNumeroTel(String numeroTel) {
        this.numeroTel = numeroTel;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getCorreoElectronico() {
        return this.correoElectronico;
    }
    
    public void setCorreoElectronico(String correoElectronico) {
        this.correoElectronico = correoElectronico;
    }
    public Set<Srmenu> getSrmenus() {
        return this.srmenus;
    }
    
    public void setSrmenus(Set<Srmenu> srmenus) {
        this.srmenus = srmenus;
    }
    public Set<Srentrenimiento> getSrentrenimientos() {
        return this.srentrenimientos;
    }
    
    public void setSrentrenimientos(Set<Srentrenimiento> srentrenimientos) {
        this.srentrenimientos = srentrenimientos;
    }
    public Set<Srsalon> getSrsalons() {
        return this.srsalons;
    }
    
    public void setSrsalons(Set<Srsalon> srsalons) {
        this.srsalons = srsalons;
    }




}


