package org;
// Generated 23/11/2014 12:27:01 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Entretenimiento generated by hbm2java
 */
public class Entretenimiento  implements java.io.Serializable {


     private Integer idEntretenimiento;
     private String tipoEntretenimiento;
     private int horas;
     private float precio;
     private Set<Srentrenimiento> srentrenimientos = new HashSet<Srentrenimiento>(0);

    public Entretenimiento() {
    }

	
    public Entretenimiento(String tipoEntretenimiento, int horas, float precio) {
        this.tipoEntretenimiento = tipoEntretenimiento;
        this.horas = horas;
        this.precio = precio;
    }
    public Entretenimiento(String tipoEntretenimiento, int horas, float precio, Set<Srentrenimiento> srentrenimientos) {
       this.tipoEntretenimiento = tipoEntretenimiento;
       this.horas = horas;
       this.precio = precio;
       this.srentrenimientos = srentrenimientos;
    }
   
    public Integer getIdEntretenimiento() {
        return this.idEntretenimiento;
    }
    
    public void setIdEntretenimiento(Integer idEntretenimiento) {
        this.idEntretenimiento = idEntretenimiento;
    }
    public String getTipoEntretenimiento() {
        return this.tipoEntretenimiento;
    }
    
    public void setTipoEntretenimiento(String tipoEntretenimiento) {
        this.tipoEntretenimiento = tipoEntretenimiento;
    }
    public int getHoras() {
        return this.horas;
    }
    
    public void setHoras(int horas) {
        this.horas = horas;
    }
    public float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(float precio) {
        this.precio = precio;
    }
    public Set<Srentrenimiento> getSrentrenimientos() {
        return this.srentrenimientos;
    }
    
    public void setSrentrenimientos(Set<Srentrenimiento> srentrenimientos) {
        this.srentrenimientos = srentrenimientos;
    }




}


