package org;
// Generated 22/11/2014 11:26:43 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Entretenimiento generated by hbm2java
 */
public class Entretenimiento  implements java.io.Serializable {


     private Integer idEntretenimiento;
     private String tipoEntretenimiento;
     private String horas;
     private float precio;
     private Set<Statusreservacionentre> statusreservacionentres = new HashSet<Statusreservacionentre>(0);

    public Entretenimiento() {
    }

	
    public Entretenimiento(String tipoEntretenimiento, String horas, float precio) {
        this.tipoEntretenimiento = tipoEntretenimiento;
        this.horas = horas;
        this.precio = precio;
    }
    public Entretenimiento(String tipoEntretenimiento, String horas, float precio, Set<Statusreservacionentre> statusreservacionentres) {
       this.tipoEntretenimiento = tipoEntretenimiento;
       this.horas = horas;
       this.precio = precio;
       this.statusreservacionentres = statusreservacionentres;
    }
   
    public Integer getIdEntretenimiento() {
        return this.idEntretenimiento;
    }
    
    public void setIdEntretenimiento(Integer idEntretenimiento) {
        this.idEntretenimiento = idEntretenimiento;
    }
    public String getTipoEntretenimiento() {
        return this.tipoEntretenimiento;
    }
    
    public void setTipoEntretenimiento(String tipoEntretenimiento) {
        this.tipoEntretenimiento = tipoEntretenimiento;
    }
    public String getHoras() {
        return this.horas;
    }
    
    public void setHoras(String horas) {
        this.horas = horas;
    }
    public float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(float precio) {
        this.precio = precio;
    }
    public Set<Statusreservacionentre> getStatusreservacionentres() {
        return this.statusreservacionentres;
    }
    
    public void setStatusreservacionentres(Set<Statusreservacionentre> statusreservacionentres) {
        this.statusreservacionentres = statusreservacionentres;
    }




}


