package org;
// Generated 22/11/2014 09:15:36 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Menu generated by hbm2java
 */
public class Menu  implements java.io.Serializable {


     private Integer idMenu;
     private String menuDes;
     private float precio;
     private int cantidadPersonas;
     private Set<Srmenu> srmenus = new HashSet<Srmenu>(0);

    public Menu() {
    }

	
    public Menu(String menuDes, float precio, int cantidadPersonas) {
        this.menuDes = menuDes;
        this.precio = precio;
        this.cantidadPersonas = cantidadPersonas;
    }
    public Menu(String menuDes, float precio, int cantidadPersonas, Set<Srmenu> srmenus) {
       this.menuDes = menuDes;
       this.precio = precio;
       this.cantidadPersonas = cantidadPersonas;
       this.srmenus = srmenus;
    }
   
    public Integer getIdMenu() {
        return this.idMenu;
    }
    
    public void setIdMenu(Integer idMenu) {
        this.idMenu = idMenu;
    }
    public String getMenuDes() {
        return this.menuDes;
    }
    
    public void setMenuDes(String menuDes) {
        this.menuDes = menuDes;
    }
    public float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(float precio) {
        this.precio = precio;
    }
    public int getCantidadPersonas() {
        return this.cantidadPersonas;
    }
    
    public void setCantidadPersonas(int cantidadPersonas) {
        this.cantidadPersonas = cantidadPersonas;
    }
    public Set<Srmenu> getSrmenus() {
        return this.srmenus;
    }
    
    public void setSrmenus(Set<Srmenu> srmenus) {
        this.srmenus = srmenus;
    }




}


