package org;
// Generated 23/11/2014 01:08:00 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Menu generated by hbm2java
 */
public class Menu  implements java.io.Serializable {


     private Integer idMenu;
     private String menuDes;
     private String nombreCompaniaMenu;
     private float precioMenu;
     private int cantidadPersonas;
     private Set<Srmenu> srmenus = new HashSet<Srmenu>(0);

    public Menu() {
    }

	
    public Menu(String menuDes, String nombreCompaniaMenu, float precioMenu, int cantidadPersonas) {
        this.menuDes = menuDes;
        this.nombreCompaniaMenu = nombreCompaniaMenu;
        this.precioMenu = precioMenu;
        this.cantidadPersonas = cantidadPersonas;
    }
    public Menu(String menuDes, String nombreCompaniaMenu, float precioMenu, int cantidadPersonas, Set<Srmenu> srmenus) {
       this.menuDes = menuDes;
       this.nombreCompaniaMenu = nombreCompaniaMenu;
       this.precioMenu = precioMenu;
       this.cantidadPersonas = cantidadPersonas;
       this.srmenus = srmenus;
    }
   
    public Integer getIdMenu() {
        return this.idMenu;
    }
    
    public void setIdMenu(Integer idMenu) {
        this.idMenu = idMenu;
    }
    public String getMenuDes() {
        return this.menuDes;
    }
    
    public void setMenuDes(String menuDes) {
        this.menuDes = menuDes;
    }
    public String getNombreCompaniaMenu() {
        return this.nombreCompaniaMenu;
    }
    
    public void setNombreCompaniaMenu(String nombreCompaniaMenu) {
        this.nombreCompaniaMenu = nombreCompaniaMenu;
    }
    public float getPrecioMenu() {
        return this.precioMenu;
    }
    
    public void setPrecioMenu(float precioMenu) {
        this.precioMenu = precioMenu;
    }
    public int getCantidadPersonas() {
        return this.cantidadPersonas;
    }
    
    public void setCantidadPersonas(int cantidadPersonas) {
        this.cantidadPersonas = cantidadPersonas;
    }
    public Set<Srmenu> getSrmenus() {
        return this.srmenus;
    }
    
    public void setSrmenus(Set<Srmenu> srmenus) {
        this.srmenus = srmenus;
    }




}


