package org;
// Generated 22/11/2014 11:26:43 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Paquetecomida generated by hbm2java
 */
public class Paquetecomida  implements java.io.Serializable {


     private Integer idPaqueteComida;
     private String menu;
     private float precio;
     private Integer cantidadPersonas;
     private Set<Statusreservacioncomida> statusreservacioncomidas = new HashSet<Statusreservacioncomida>(0);

    public Paquetecomida() {
    }

	
    public Paquetecomida(String menu, float precio) {
        this.menu = menu;
        this.precio = precio;
    }
    public Paquetecomida(String menu, float precio, Integer cantidadPersonas, Set<Statusreservacioncomida> statusreservacioncomidas) {
       this.menu = menu;
       this.precio = precio;
       this.cantidadPersonas = cantidadPersonas;
       this.statusreservacioncomidas = statusreservacioncomidas;
    }
   
    public Integer getIdPaqueteComida() {
        return this.idPaqueteComida;
    }
    
    public void setIdPaqueteComida(Integer idPaqueteComida) {
        this.idPaqueteComida = idPaqueteComida;
    }
    public String getMenu() {
        return this.menu;
    }
    
    public void setMenu(String menu) {
        this.menu = menu;
    }
    public float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(float precio) {
        this.precio = precio;
    }
    public Integer getCantidadPersonas() {
        return this.cantidadPersonas;
    }
    
    public void setCantidadPersonas(Integer cantidadPersonas) {
        this.cantidadPersonas = cantidadPersonas;
    }
    public Set<Statusreservacioncomida> getStatusreservacioncomidas() {
        return this.statusreservacioncomidas;
    }
    
    public void setStatusreservacioncomidas(Set<Statusreservacioncomida> statusreservacioncomidas) {
        this.statusreservacioncomidas = statusreservacioncomidas;
    }




}


