package org;
// Generated 22/11/2014 11:26:43 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Salon generated by hbm2java
 */
public class Salon  implements java.io.Serializable {

     private Integer idSalon;
     private String nombreSalon;
     private float precio;
     private String direccion;
     private Set<Statusreservacionsalon> statusreservacionsalons = new HashSet<Statusreservacionsalon>(0);

    public Salon() {
    }

	
    public Salon(String nombreSalon, float precio, String direccion) {
        this.nombreSalon = nombreSalon;
        this.precio = precio;
        this.direccion = direccion;
    }
    public Salon(Integer idSalon, String nombreSalon, float precio, String direccion) {
        this.idSalon=idSalon;
        this.nombreSalon = nombreSalon;
        this.precio = precio;
        this.direccion = direccion;
    }
    public Salon(String nombreSalon, float precio, String direccion, Set<Statusreservacionsalon> statusreservacionsalons) {
       this.nombreSalon = nombreSalon;
       this.precio = precio;
       this.direccion = direccion;
       this.statusreservacionsalons = statusreservacionsalons;
    }
   
    public Integer getIdSalon() {
        return this.idSalon;
    }
    
    public void setIdSalon(Integer idSalon) {
        this.idSalon = idSalon;
    }
    public String getNombreSalon() {
        return this.nombreSalon;
    }
    
    public void setNombreSalon(String nombreSalon) {
        this.nombreSalon = nombreSalon;
    }
    public float getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(float precio) {
        this.precio = precio;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public Set<Statusreservacionsalon> getStatusreservacionsalons() {
        return this.statusreservacionsalons;
    }
    
    public void setStatusreservacionsalons(Set<Statusreservacionsalon> statusreservacionsalons) {
        this.statusreservacionsalons = statusreservacionsalons;
    }




}


