package org;
// Generated 29/11/2014 08:44:03 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Srentrenimiento generated by hbm2java
 */
public class Srentrenimiento  implements java.io.Serializable {


     private Integer idSrentrenimiento;
     private Entretenimiento entretenimiento;
     private Date fechaEntretenimiento;
     private Date fechaReservacionEntretenimiento;
     private String statusEntretenimiento;
     private String correoClienteEntretenimiento;

    public Srentrenimiento() {
    }

    public Srentrenimiento(Entretenimiento entretenimiento, Date fechaEntretenimiento, Date fechaReservacionEntretenimiento, String statusEntretenimiento, String correoClienteEntretenimiento) {
       this.entretenimiento = entretenimiento;
       this.fechaEntretenimiento = fechaEntretenimiento;
       this.fechaReservacionEntretenimiento = fechaReservacionEntretenimiento;
       this.statusEntretenimiento = statusEntretenimiento;
       this.correoClienteEntretenimiento = correoClienteEntretenimiento;
    }
   
    public Integer getIdSrentrenimiento() {
        return this.idSrentrenimiento;
    }
    
    public void setIdSrentrenimiento(Integer idSrentrenimiento) {
        this.idSrentrenimiento = idSrentrenimiento;
    }
    public Entretenimiento getEntretenimiento() {
        return this.entretenimiento;
    }
    
    public void setEntretenimiento(Entretenimiento entretenimiento) {
        this.entretenimiento = entretenimiento;
    }
    public Date getFechaEntretenimiento() {
        return this.fechaEntretenimiento;
    }
    
    public void setFechaEntretenimiento(Date fechaEntretenimiento) {
        this.fechaEntretenimiento = fechaEntretenimiento;
    }
    public Date getFechaReservacionEntretenimiento() {
        return this.fechaReservacionEntretenimiento;
    }
    
    public void setFechaReservacionEntretenimiento(Date fechaReservacionEntretenimiento) {
        this.fechaReservacionEntretenimiento = fechaReservacionEntretenimiento;
    }
    public String getStatusEntretenimiento() {
        return this.statusEntretenimiento;
    }
    
    public void setStatusEntretenimiento(String statusEntretenimiento) {
        this.statusEntretenimiento = statusEntretenimiento;
    }
    public String getCorreoClienteEntretenimiento() {
        return this.correoClienteEntretenimiento;
    }
    
    public void setCorreoClienteEntretenimiento(String correoClienteEntretenimiento) {
        this.correoClienteEntretenimiento = correoClienteEntretenimiento;
    }




}


