package org;
// Generated 23/11/2014 02:27:29 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Srentrenimiento generated by hbm2java
 */
public class Srentrenimiento  implements java.io.Serializable {


     private Integer idSrentrenimiento;
     private Entretenimiento entretenimiento;
     private Date fechaEntretenimiento;
     private String statusEntretenimiento;

    public Srentrenimiento() {
    }

    public Srentrenimiento(Entretenimiento entretenimiento, Date fechaEntretenimiento, String statusEntretenimiento) {
       this.entretenimiento = entretenimiento;
       this.fechaEntretenimiento = fechaEntretenimiento;
       this.statusEntretenimiento = statusEntretenimiento;
    }
   
    public Integer getIdSrentrenimiento() {
        return this.idSrentrenimiento;
    }
    
    public void setIdSrentrenimiento(Integer idSrentrenimiento) {
        this.idSrentrenimiento = idSrentrenimiento;
    }
    public Entretenimiento getEntretenimiento() {
        return this.entretenimiento;
    }
    
    public void setEntretenimiento(Entretenimiento entretenimiento) {
        this.entretenimiento = entretenimiento;
    }
    public Date getFechaEntretenimiento() {
        return this.fechaEntretenimiento;
    }
    
    public void setFechaEntretenimiento(Date fechaEntretenimiento) {
        this.fechaEntretenimiento = fechaEntretenimiento;
    }
    public String getStatusEntretenimiento() {
        return this.statusEntretenimiento;
    }
    
    public void setStatusEntretenimiento(String statusEntretenimiento) {
        this.statusEntretenimiento = statusEntretenimiento;
    }




}


