package org;
// Generated 29/11/2014 08:44:03 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Srmenu generated by hbm2java
 */
public class Srmenu  implements java.io.Serializable {


     private Integer idSrmenu;
     private Menu menu;
     private String stautsMenu;
     private Date fechaMenu;
     private Date fechaReservacionMenu;
     private String correoClienteMenu;

    public Srmenu() {
    }

    public Srmenu(Menu menu, String stautsMenu, Date fechaMenu, Date fechaReservacionMenu, String correoClienteMenu) {
       this.menu = menu;
       this.stautsMenu = stautsMenu;
       this.fechaMenu = fechaMenu;
       this.fechaReservacionMenu = fechaReservacionMenu;
       this.correoClienteMenu = correoClienteMenu;
    }
   
    public Integer getIdSrmenu() {
        return this.idSrmenu;
    }
    
    public void setIdSrmenu(Integer idSrmenu) {
        this.idSrmenu = idSrmenu;
    }
    public Menu getMenu() {
        return this.menu;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
    }
    public String getStautsMenu() {
        return this.stautsMenu;
    }
    
    public void setStautsMenu(String stautsMenu) {
        this.stautsMenu = stautsMenu;
    }
    public Date getFechaMenu() {
        return this.fechaMenu;
    }
    
    public void setFechaMenu(Date fechaMenu) {
        this.fechaMenu = fechaMenu;
    }
    public Date getFechaReservacionMenu() {
        return this.fechaReservacionMenu;
    }
    
    public void setFechaReservacionMenu(Date fechaReservacionMenu) {
        this.fechaReservacionMenu = fechaReservacionMenu;
    }
    public String getCorreoClienteMenu() {
        return this.correoClienteMenu;
    }
    
    public void setCorreoClienteMenu(String correoClienteMenu) {
        this.correoClienteMenu = correoClienteMenu;
    }




}


