package org;
// Generated 29/11/2014 08:44:03 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Srsalon generated by hbm2java
 */
public class Srsalon  implements java.io.Serializable {


     private Integer idSrsalon;
     private Salon salon;
     private String statusSalon;
     private Date fechaSalon;
     private Date fechaReservacionSalon;
     private String correoClienteSalon;

    public Srsalon() {
    }

    public Srsalon(Salon salon, String statusSalon, Date fechaSalon, Date fechaReservacionSalon, String correoClienteSalon) {
       this.salon = salon;
       this.statusSalon = statusSalon;
       this.fechaSalon = fechaSalon;
       this.fechaReservacionSalon = fechaReservacionSalon;
       this.correoClienteSalon = correoClienteSalon;
    }
   
    public Integer getIdSrsalon() {
        return this.idSrsalon;
    }
    
    public void setIdSrsalon(Integer idSrsalon) {
        this.idSrsalon = idSrsalon;
    }
    public Salon getSalon() {
        return this.salon;
    }
    
    public void setSalon(Salon salon) {
        this.salon = salon;
    }
    public String getStatusSalon() {
        return this.statusSalon;
    }
    
    public void setStatusSalon(String statusSalon) {
        this.statusSalon = statusSalon;
    }
    public Date getFechaSalon() {
        return this.fechaSalon;
    }
    
    public void setFechaSalon(Date fechaSalon) {
        this.fechaSalon = fechaSalon;
    }
    public Date getFechaReservacionSalon() {
        return this.fechaReservacionSalon;
    }
    
    public void setFechaReservacionSalon(Date fechaReservacionSalon) {
        this.fechaReservacionSalon = fechaReservacionSalon;
    }
    public String getCorreoClienteSalon() {
        return this.correoClienteSalon;
    }
    
    public void setCorreoClienteSalon(String correoClienteSalon) {
        this.correoClienteSalon = correoClienteSalon;
    }




}


