package org;
// Generated 1/12/2014 10:39:03 PM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Srsalon generated by hbm2java
 */
public class Srsalon  implements java.io.Serializable {


     private Integer idSrsalon;
     private Empresacliente empresacliente;
     private Salon salon;
     private String statusSalon;
     private Date fechaReservacionSalon;
     private String correoClienteSalon;

    public Srsalon() {
    }

    public Srsalon(Empresacliente empresacliente, Salon salon, String statusSalon, Date fechaReservacionSalon, String correoClienteSalon) {
       this.empresacliente = empresacliente;
       this.salon = salon;
       this.statusSalon = statusSalon;
       this.fechaReservacionSalon = fechaReservacionSalon;
       this.correoClienteSalon = correoClienteSalon;
    }
   
    public Integer getIdSrsalon() {
        return this.idSrsalon;
    }
    
    public void setIdSrsalon(Integer idSrsalon) {
        this.idSrsalon = idSrsalon;
    }
    public Empresacliente getEmpresacliente() {
        return this.empresacliente;
    }
    
    public void setEmpresacliente(Empresacliente empresacliente) {
        this.empresacliente = empresacliente;
    }
    public Salon getSalon() {
        return this.salon;
    }
    
    public void setSalon(Salon salon) {
        this.salon = salon;
    }
    public String getStatusSalon() {
        return this.statusSalon;
    }
    
    public void setStatusSalon(String statusSalon) {
        this.statusSalon = statusSalon;
    }
    public Date getFechaReservacionSalon() {
        return this.fechaReservacionSalon;
    }
    
    public void setFechaReservacionSalon(Date fechaReservacionSalon) {
        this.fechaReservacionSalon = fechaReservacionSalon;
    }
    public String getCorreoClienteSalon() {
        return this.correoClienteSalon;
    }
    
    public void setCorreoClienteSalon(String correoClienteSalon) {
        this.correoClienteSalon = correoClienteSalon;
    }




}


