package org;
// Generated 22/11/2014 11:26:43 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Statusreservacionentre generated by hbm2java
 */
public class Statusreservacionentre  implements java.io.Serializable {


     private Integer idStatusReservacion;
     private Entretenimiento entretenimiento;
     private Date fechaReservacion;
     private String status;

    public Statusreservacionentre() {
    }

    public Statusreservacionentre(Entretenimiento entretenimiento, Date fechaReservacion, String status) {
       this.entretenimiento = entretenimiento;
       this.fechaReservacion = fechaReservacion;
       this.status = status;
    }
   
    public Integer getIdStatusReservacion() {
        return this.idStatusReservacion;
    }
    
    public void setIdStatusReservacion(Integer idStatusReservacion) {
        this.idStatusReservacion = idStatusReservacion;
    }
    public Entretenimiento getEntretenimiento() {
        return this.entretenimiento;
    }
    
    public void setEntretenimiento(Entretenimiento entretenimiento) {
        this.entretenimiento = entretenimiento;
    }
    public Date getFechaReservacion() {
        return this.fechaReservacion;
    }
    
    public void setFechaReservacion(Date fechaReservacion) {
        this.fechaReservacion = fechaReservacion;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


