package org;
// Generated 22/11/2014 11:26:43 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Statusreservacionsalon generated by hbm2java
 */
public class Statusreservacionsalon  implements java.io.Serializable {


     private Integer idStatusReservacion;
     private Salon salon;
     private Date fechaReservacion;
     private String status;

    public Statusreservacionsalon() {
    }

    public Statusreservacionsalon(Salon salon, Date fechaReservacion, String status) {
       this.salon = salon;
       this.fechaReservacion = fechaReservacion;
       this.status = status;
    }
   
    public Integer getIdStatusReservacion() {
        return this.idStatusReservacion;
    }
    
    public void setIdStatusReservacion(Integer idStatusReservacion) {
        this.idStatusReservacion = idStatusReservacion;
    }
    public Salon getSalon() {
        return this.salon;
    }
    
    public void setSalon(Salon salon) {
        this.salon = salon;
    }
    public Date getFechaReservacion() {
        return this.fechaReservacion;
    }
    
    public void setFechaReservacion(Date fechaReservacion) {
        this.fechaReservacion = fechaReservacion;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


