package org;
// Generated 22/11/2014 11:26:43 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Statusreservacioncomida generated by hbm2java
 */
public class Statusreservacioncomida  implements java.io.Serializable {


     private Integer idStatusReservacion;
     private Paquetecomida paquetecomida;
     private Date fechaReservacion;
     private String status;

    public Statusreservacioncomida() {
    }

    public Statusreservacioncomida(Paquetecomida paquetecomida, Date fechaReservacion, String status) {
       this.paquetecomida = paquetecomida;
       this.fechaReservacion = fechaReservacion;
       this.status = status;
    }
   
    public Integer getIdStatusReservacion() {
        return this.idStatusReservacion;
    }
    
    public void setIdStatusReservacion(Integer idStatusReservacion) {
        this.idStatusReservacion = idStatusReservacion;
    }
    public Paquetecomida getPaquetecomida() {
        return this.paquetecomida;
    }
    
    public void setPaquetecomida(Paquetecomida paquetecomida) {
        this.paquetecomida = paquetecomida;
    }
    public Date getFechaReservacion() {
        return this.fechaReservacion;
    }
    
    public void setFechaReservacion(Date fechaReservacion) {
        this.fechaReservacion = fechaReservacion;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


